[Middleware Frontend] Package list organism
crowdform/stonks-react pull request #3
Opened 2023-02-03 17:35 UTC by givbnu

2023-02-03 20:51 UTC, copocaneta requested changes
@givbnu, conflict, please fix and get back

2023-02-06 13:01 UTC, copocaneta requested changes

2023-02-06 13:01 UTC, copocaneta commented on src/components/molecules/PackageListPopover.jsx
> +  const [isOpen, setIsOpen] = useBoolean();
Chakra UI has its own `useDisclosure()` system to monitor the popover being opened or closed.

```js
const { isOpen, onToggle, onClose } = useDisclosure()
```

Did you have some issue using it? Or is it something I am not seeing here?

2023-02-06 15:55 UTC, givbnu commented on src/components/molecules/PackageListPopover.jsx
> +  const [isOpen, setIsOpen] = useBoolean();
No, just a beginner mistake. I copied the code from the indicated block on the chakra website and that block was using useBoolean instead of useDisclosure. Fixed

2023-02-06 19:44 UTC, closed without merging